# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(['KPK_2_9.py'],
             pathex=['C:/Users/yaidf/2й_Год/cave'],
             binaries=[],
             datas=[('data/alhimiy.png', 'data'),
             ('data/boat.png', 'data'),
             ('data/bones.png', 'data'),
             ('data/Boss.png', 'data'),
             ('data/btnReStart.png', 'data'),
             ('data/btnReStart2.png', 'data'),
             ('data/btnStart.png', 'data'),
             ('data/btnStart2.png', 'data'),
             ('data/c4106e6e2d434ce492e99ba7cb85249c--arte-pixel-pixel-art.jpg', 'data'),
             ('data/cave.png', 'data'),
             ('data/cells.png', 'data'),
             ('data/cells2.png', 'data'),
             ('data/chesat.png', 'data'),
             ('data/chest.png', 'data'),
             ('data/chest2.png', 'data'),
             ('data/click.mp3', 'data'),
             ('data/cockroach.png', 'data'),
             ('data/def.png', 'data'),
             ('data/door.png', 'data'),
             ('data/DZ-oznhXcAUynkV.jpg', 'data'),
             ('data/e62af218bcc7a9ac8e05bf053f9a52fd.jpg', 'data'),
             ('data/enchantment.mp3', 'data'),
             ('data/enchantment.ogg', 'data'),
             ('data/eyes.jpg', 'data'),
             ('data/floor3.png', 'data'),
             ('data/flor.png', 'data'),
             ('data/hallo.mp3', 'data'),
             ('data/hero.png', 'data'),
             ('data/heroD.png', 'data'),
             ('data/heroImage.png', 'data'),
             ('data/hill.jpg', 'data'),
             ('data/hill.png', 'data'),
             ('data/i.webp', 'data'),
             ('data/inventory.png', 'data'),
             ('data/kiss.gif', 'data'),
             ('data/logo.png', 'data'),
             ('data/m0.png', 'data'),
             ('data/m1.png', 'data'),
             ('data/m2.png', 'data'),
             ('data/m3.png', 'data'),
             ('data/m4.png', 'data'),
             ('data/m5.png', 'data'),
             ('data/m6.gif', 'data'),
             ('data/m6.png', 'data'),
             ('data/maxresdefault.jpg', 'data'),
             ('data/meditation.png', 'data'),
             ('data/money.png', 'data'),
             ('data/monstor.png', 'data'),
             ('data/person.png', 'data'),
             ('data/person2.png', 'data'),
             ('data/PushkiPushka.png', 'data'),
             ('data/RudeBuster.mp3', 'data'),
             ('data/s1.png', 'data'),
             ('data/s2.png', 'data'),
             ('data/s3.png', 'data'),
             ('data/shop.png', 'data'),
             ('data/show.png', 'data'),
             ('data/slime.gif', 'data'),
             ('data/ss.gif', 'data'),
             ('data/start.png', 'data'),
             ('data/sword.jpg', 'data'),
             ('data/sword.png', 'data'),
             ('data/tap.mp3', 'data'),
             ('data/TextFon.png', 'data'),
             ('data/torch.gif', 'data'),
             ('data/trap.png', 'data'),
             ('data/Седнев.jpg', 'data'),
             ('data/Седнев.png', 'data')],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='KPK2',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=False )
